@startuml
actor User
participant "应用" as APP
participant "配置MCP工具" as MCPServerTools
participant "UV/UVX/NPX" as ExeTools
participant "LLM" as LLM
participant "MCP 客户端" as MCPClient
participant "MPC 网关" as SuperGateway
participant "MCP 服务端" as MCPServer

User -> APP: 打开应用
APP -> MCPServerTools: 配置工具集
MCPServerTools -> ExeTools: APP主进程拉起服务端进程(stdio形式***REMOVED***
ExeTools -> MCPServer: 启动MCP服务
MCPServer -> MCPServer: 后台运行
MCPServer -> MCPServer: 等待客户端连接
MCPServerTools -[#red]-> SuperGateway: 启动MCP网关(sse形式***REMOVED***
SuperGateway -[#red]-> MCPServer: 启动MCP服务
SuperGateway -[#red]-> SuperGateway: 后台运行
SuperGateway -[#red]-> SuperGateway: 等待客户端连接

User -> APP: 提出问题
APP -> MCPServerTools: 发送问题并获取配置工具集
MCPServerTools -> LLM: 传递问题和工具集
LLM -> LLM: 根据问题选择可用工具
LLM -> APP: 返回选择的工具
APP -> MCPClient: 按顺序调用选择的工具
MCPClient -[#red]-> SuperGateway: 本地应用主进程调用MCP网关(sse形式***REMOVED***
SuperGateway -[#red]-> MCPServer: 调用MCP服务端
MCPClient -> MCPServer: 本地应用主进程调用MCP服务端子进程(stdio形式***REMOVED***
MCPServer -> MCPServer: 处理客户端请求
MCPServer -> LLM: 返回执行结果
LLM -> LLM: 总结结果
LLM -> APP: 生成最终回答
APP -> User: 提供最终回答
@enduml